services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bitnami/laravel
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    environment:
      - APP_ENV=local
    volumes:
      - ./:/var/www
    networks:
      - laravel

  # Nginx Service
  web:
    image: nginx:alpine
    container_name: laravel_web
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  # PostgreSQL Service
  db:
    image: postgres:15
    container_name: laravel_postgres
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laraveluser
      POSTGRES_PASSWORD: laravelpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

# Volumes
volumes:
  pgdata:

# Networks
networks:
  laravel:
    driver: bridge
